In [1]:
import numpy as np


In [2]:
arr = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr.shape

(3, 3)

In [4]:
arr.size

9

In [5]:
arr.ndim

2

In [6]:
arr.dtype

dtype('int32')

In [7]:
arr = np.arange(40)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [8]:
arr = np.arange(0,100,10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
arr = np.linspace(0,100,5)
arr

array([  0.,  25.,  50.,  75., 100.])

In [11]:
arr = np.linspace(0,50,10)
arr

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [13]:
arr = np.zeros(10, dtype=np.float)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
arr = np.ones(50, dtype=np.float64)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
arr = np.eye(10)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
arr = np.full((5,5),8)
arr

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [17]:
arr = np.random.rand(5,5)
arr

array([[0.62091176, 0.2047704 , 0.94193923, 0.39186271, 0.41553133],
       [0.45271272, 0.19153114, 0.06359278, 0.42442567, 0.66488812],
       [0.9501646 , 0.77846679, 0.88917181, 0.71333261, 0.14588416],
       [0.12556165, 0.37256937, 0.52954883, 0.4092995 , 0.97646124],
       [0.71590419, 0.05125965, 0.10481094, 0.71355537, 0.58274651]])

In [18]:
arr = np.random.rand(4,4)*50
arr

array([[3.88415538e+01, 2.86828476e+00, 9.46780607e+00, 4.30764367e+01],
       [7.72850857e-03, 1.16939466e+01, 2.29497574e+00, 1.08331831e+01],
       [1.02045308e+01, 4.59294006e+00, 2.35597125e+01, 2.78472467e+01],
       [4.05450562e+01, 4.72304224e+01, 1.75822162e+01, 4.45753633e+00]])

In [19]:
arr = np.random.randint(5,size=(5,5))
arr

array([[1, 0, 0, 1, 3],
       [3, 4, 2, 0, 3],
       [3, 3, 1, 3, 4],
       [1, 4, 2, 3, 0],
       [1, 3, 2, 0, 4]])

In [20]:
arr.tolist()

[[1, 0, 0, 1, 3],
 [3, 4, 2, 0, 3],
 [3, 3, 1, 3, 4],
 [1, 4, 2, 3, 0],
 [1, 3, 2, 0, 4]]

In [22]:
#copy

arr1 = np.copy(arr)
arr1

array([[1, 0, 0, 1, 3],
       [3, 4, 2, 0, 3],
       [3, 3, 1, 3, 4],
       [1, 4, 2, 3, 0],
       [1, 3, 2, 0, 4]])

In [24]:
arr2 = arr1.sort()
arr2

In [25]:
#flatten
arr3 = np.random.rand(2,2)
arr4 = arr3.flatten()
arr4

array([0.26402614, 0.88529897, 0.87194768, 0.73493436])

In [28]:
#transopose

#arr5 = arr4.T()


In [29]:
arr6 = np.arange(1,10)
arr7 = arr6.reshape(3,3)
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr8 = np.arange(0,10)
arr9 = np.resize(5,5)
arr9

array([5, 5, 5, 5, 5])

In [32]:
# combining \ splitting

arr10 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr11 = np.array([[10,20,30],[40,50,60], [70,80,90]])

arr12 = np.concatenate((arr10,arr11), axis=0)
arr12

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [33]:
arr13 = np.concatenate((arr10,arr11), axis=1)
arr13

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60],
       [ 7,  8,  9, 70, 80, 90]])

In [34]:
# indexing \ slicing\ subsetting

array_1 = np.arange(6)
array_1[0:5]

array([0, 1, 2, 3, 4])

In [36]:
arra_2 = np.random.randint(10, size=(5,5))
arra_2[:,4]

array([1, 7, 1, 8, 1])

In [37]:
# scalar math

arr_s = np.arange(10)
print(np.add(arr_s, 1))

[ 1  2  3  4  5  6  7  8  9 10]


In [38]:
print(np.subtract(arr_s, 2))

[-2 -1  0  1  2  3  4  5  6  7]


In [39]:
print(np.multiply(arr_s, 2))

[ 0  2  4  6  8 10 12 14 16 18]


In [41]:
print(np.divide(arr_s, 2))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [42]:
print(np.power(arr_s, 2))

[ 0  1  4  9 16 25 36 49 64 81]


In [43]:
#vector math
arr_v = np.arange(10)
arr_v

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
print(np.add(arr_s, arr_v))

[ 0  2  4  6  8 10 12 14 16 18]


In [46]:
print(np.subtract(arr_s, arr_v))

[0 0 0 0 0 0 0 0 0 0]


In [47]:
print(np.multiply(arr_s, arr_v))

[ 0  1  4  9 16 25 36 49 64 81]


In [48]:
print(np.divide(arr_s, arr_v))

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


C:\Users\USER\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [49]:
print(np.power(arr_s, arr_v))

[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]


In [50]:
#statistics

arr_st = np.arange(50)
arr_st

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [52]:
print(np.mean(arr_st))

24.5


In [54]:
print(np.std(arr_st))

14.430869689661812


In [55]:
print(np.sum(arr_st))

1225


In [56]:
print(np.min(arr_st))

0


In [57]:
print(np.max(arr_st))

49


In [58]:
print(np.var(arr_st))

208.25
